### ISSUE TITLE
Getting Error when trying to generate the Schema

### ISSUE THREAD

**Issue by ragvi2000** [benedwards44/schemalister#10]
When I try to get Schema after providing valid credentials, I am getting the below error.

![Fig1](https://user-images.githubusercontent.com/87134297/124932902-73451c00-dfd1-11eb-9820-ed4d175c101c.png)
500 - Website Error -- There appears to have been an error. The administrator has been notified.

I have tried different org and different browsers, same issue.

**Comment by mkeppy2** [comment]
I have the exact same problem. I've tried in multiple orgs where the tool used to work and I've been getting the same errors.   Any workarounds?

**Comment by benedwards44** [comment]
I've flushed the database and reset the server, seems to be working now.
