### ISSUE TITLE
500 - Website Error

### ISSUE THREAD

**Issue by CloudTechRaz** [benedwards44/schemalister#17]
Seems to be an issue with the site at the moment. Would a service restart help?

Cheers
Raz

**Comment by meighanvorys** [comment]
I'm having the same issue - when i try to use Schema Lister it goes to an Error 500 page.

**Comment by ddelgado321** [comment]
I'm having the same issue today. Any idea on when is it going live again?

**Comment by benedwards44** [comment]
I've restarted the app, seems to be back up and running.

Sorry peeps!
