### ISSUE TITLE
No attribute 'StringIO' error on Export To XLSX (Single Tab)

### ISSUE THREAD

**Issue by gwickman** [benedwards44/schemalister#19]
Great application, thank you for building and maintaining it! When choosing "Export To XLSX (Single Tab)" using the tool in Chrome I am recieving the following error:

type object '_io.StringIO' has no attribute 'StringIO'

This error is presented as a replacement for the page with no formatting - screen shot attached.

I have tried using Chrome from two different accounts and different Salesforce instances but get the same error.

![image](https://user-images.githubusercontent.com/8178270/217821293-b628d264-88f8-4f69-845d-40cb0cbcb4c2.png)

**Comment by benedwards44** [comment]
Apologies, I updated the app to Django 4 and Python 3 yesterday and needed to update the export logic.

Should be working now!
