### ISSUE TITLE
Any reason fields from mananged packages are not included?

### ISSUE THREAD

**Issue by muchavie** [benedwards44/schemalister#2]
I ran schema lister on an NPSP Org.   NPSP adds tops of fields to Account, Contact, Opportunity.  Not seeing these.   Getting a list of these fields in particular is why I ran the too.

Thanks! Peter

**Comment by benedwards44** [comment]
@muchavie there is an option to "Include Managed Package Objects". Did you check this box?

**Comment by muchavie** [comment]
Yes!  That was the problem.   I did take a while to run but it eventually came through.

Many Thanks, Peter

**Comment by benedwards44** [comment]
Yep including Managed Package objects takes quite a bit more time as it normally adds quite a lot more metadata to scan through!
