### ISSUE TITLE
Not getting description field.

### ISSUE THREAD

**Issue by MTabishKhan** [benedwards44/schemalister#3]
I ran the schemalister to extract all the fields along with there description, but except description field all the information is present. Can you check and let me know.

**Comment by benedwards44** [comment]
The Description field isn't included in the describe call via the REST API, which is what the app uses. So it's not available sorry.

You can validate that yourself from this doc:
https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_sobject_describe.htm

**Comment by MTabishKhan** [comment]
Hello Edward,

Thanks a lot Edwards for your reply. Actually, I am using your code for a
project requirement. If you can let me know how I can run this code in my
system without using Heroku it will be really helpful and also can I
include the Description field in the describe call of the REST API.

Regards
Mohammed

Regards

Mohammed Tabish Khan


*Senior Software Engineer | AHM Data Division | Indecomm Global Services
(India) Private Limited | *

*Brigade South Parade, # 10, MG Road**,Bangalore-560 001|Phone: +91
9036467271 **| *

*Email: **Mohammed.Khan@indecomm.net* <Mohammed.Khan@indecomm.net>* | *
*www.indecomm.net* <http://www.indecomm.net/>

**Comment by benedwards44** [comment]
Hi Mohammed, 

Just to be clear, the Description IS NOT included in the REST API, hence why it's not included in the app. You will need to use the Metadata API (or Tooling API) to get the description field.

**Comment by MTabishKhan** [comment]
Is there any possibility of including the Description field in the REST API, or can you please share the REST API code or place where can I access it. 

Regards
Mohammed

**Comment by MTabishKhan** [comment]
Thanks for the help Edward, I will check the README.md file once you have uploaded it. 

Thanks Again!
Mohammed.
