### ISSUE TITLE
Server responded with a 500 status code response

### ISSUE THREAD

**Issue by juanchiansaldi** [benedwards44/schemalister#9]
The application is still working?

**Comment by redmondke** [comment]
Running into the same error message on 6/2/2021. Last week, I did not see the same error, but the system timed out before I received any results. Image below:

![image](https://user-images.githubusercontent.com/82827792/120535505-0e364f00-c3b1-11eb-86d6-0960edc90c3f.png)

**Comment by Josecjr** [comment]
same error here. 06/03/21

**Comment by benedwards44** [comment]
Should be fixed now!

**Comment by redmondke** [comment]
Thank you for the fix! It's working now 👍🏻

**Comment by ragvi2000** [comment]
The same issue happening again now...
![Fig1](https://user-images.githubusercontent.com/87134297/124933756-2150c600-dfd2-11eb-9f4c-aa2adad50961.png)
